name: Nightly Snapshot of Release Download Statistics

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 1:00 AM UTC
workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug


jobs:
  collect-stats:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the release-stats branch
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: release-stats  # Specify the branch to check out

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. Install required Python dependencies
    - name: Install dependencies
      run: |
        pip install requests pandas

    # 4. Run the Python script to fetch and append download stats
    - name: Run Python script to fetch and append download stats
      run: python .github/scripts/fetch_and_append_stats.py

    # 5. Configure Git for committing
    - name: Configure Git
      run: |
        git config --local user.email "mitja.sailer@sap.com"
        git config --local user.name "nice2mitja"

    # 6. Fetch the latest changes from the remote branch
    - name: Fetch latest changes
      run: |
        git fetch origin release-stats

    # 7. Rebase the latest changes
    - name: Rebase changes
      run: |
        git rebase origin/release-stats || { echo "Rebase failed, resolving conflicts"; exit 1; }

    # 8. Commit and push the changes back to the release-stats branch
    - name: Commit changes
      run: |
        git add release_stats.csv
        git commit -m "Add nightly snapshot for $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push -f origin release-stats
